# Generated by Django 4.1.7 on 2023-02-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LinkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_key", models.CharField(max_length=50, unique=True)),
                ("link", models.TextField()),
            ],
        ),
    ]
